### ISSUE TITLE
Only One tine document is scanned

### ISSUE THREAD

**Issue by spatil063** [Aniruddha-Tapas/Document-Scanner#1]
Actually i want number of document to be scanned.Library is allowing us to take one picture at time and finishes again we have to start.I want this app for multiple documents and functionality of grouping the items together means After scanned documents must be grouped according to the date or use.

**Comment by Aniruddha-Tapas** [comment]
Hi! Yes the app currently hasn't incorporated the grouping functionality as you suggested. It would surely be something I would take care of during the next update. Regarding the multiple documents issue; the app is built to scan a document first, preprocess it, and display it to the user to review. Once the user confirms to use the scanned document, the scan is saved and the user is taken back to Camera activity for another scan. Hence to take multiple documents, what you could do is scan those docs sequentially and then use the GalleryGridActivity to sort/share the scans according to your use to manually group them.
